-- Merveil AI External Developer Platform V2
-- Adds usage analytics, distributed rate limiting, webhooks and OAuth client registration.
create table if not exists public.api_usage_logs (id uuid primary key default gen_random_uuid(), application_id uuid not null references public.api_applications(id) on delete cascade, user_id uuid not null, method text not null, path text not null, status_code integer, request_id text not null, latency_ms integer, created_at timestamptz not null default now());
create index if not exists api_usage_logs_app_created_idx on public.api_usage_logs(application_id, created_at desc);
create table if not exists public.api_rate_buckets (application_id uuid not null references public.api_applications(id) on delete cascade, bucket_start timestamptz not null, request_count integer not null default 0, primary key(application_id,bucket_start));
create or replace function public.consume_api_rate_limit(p_application_id uuid,p_bucket_start timestamptz,p_limit integer) returns boolean language plpgsql security definer set search_path=public as $$ declare v_count integer; begin insert into public.api_rate_buckets(application_id,bucket_start,request_count) values(p_application_id,p_bucket_start,1) on conflict(application_id,bucket_start) do update set request_count=public.api_rate_buckets.request_count+1 returning request_count into v_count; return v_count <= p_limit; end; $$;
revoke all on function public.consume_api_rate_limit(uuid,timestamptz,integer) from public;
do $$ begin alter table public.api_applications add column if not exists description text; alter table public.api_applications add column if not exists redirect_uris text[] not null default '{}'; alter table public.api_applications add column if not exists webhook_url text; alter table public.api_applications add column if not exists webhook_secret_hash text; alter table public.api_applications add column if not exists updated_at timestamptz not null default now(); exception when undefined_table then null; end $$;
create table if not exists public.api_webhooks (id uuid primary key default gen_random_uuid(),application_id uuid not null references public.api_applications(id) on delete cascade,url text not null,events text[] not null default '{}',secret_hash text,status text not null default 'active' check(status in ('active','disabled')),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create index if not exists api_webhooks_app_idx on public.api_webhooks(application_id);
create table if not exists public.api_oauth_clients (id uuid primary key default gen_random_uuid(),application_id uuid not null references public.api_applications(id) on delete cascade,client_id text not null unique,client_secret_hash text not null,redirect_uris text[] not null default '{}',scopes text[] not null default '{}',status text not null default 'active' check(status in ('active','revoked')),created_at timestamptz not null default now());
create index if not exists api_oauth_clients_app_idx on public.api_oauth_clients(application_id);
alter table public.api_usage_logs enable row level security; alter table public.api_rate_buckets enable row level security; alter table public.api_webhooks enable row level security; alter table public.api_oauth_clients enable row level security;
drop policy if exists api_usage_owner_select on public.api_usage_logs; create policy api_usage_owner_select on public.api_usage_logs for select using(auth.uid()=user_id);
drop policy if exists api_webhooks_owner_all on public.api_webhooks; create policy api_webhooks_owner_all on public.api_webhooks for all using(exists(select 1 from public.api_applications a where a.id=application_id and a.user_id=auth.uid())) with check(exists(select 1 from public.api_applications a where a.id=application_id and a.user_id=auth.uid()));
drop policy if exists api_oauth_owner_all on public.api_oauth_clients; create policy api_oauth_owner_all on public.api_oauth_clients for all using(exists(select 1 from public.api_applications a where a.id=application_id and a.user_id=auth.uid())) with check(exists(select 1 from public.api_applications a where a.id=application_id and a.user_id=auth.uid()));
