import crypto from 'node:crypto';
import { createClient } from '@supabase/supabase-js';
import { decryptWebhookSecret } from '../../server/merveil-v1/webhook-secret.js';
const supabase=createClient(process.env.SUPABASE_URL,process.env.SUPABASE_SERVICE_ROLE_KEY);
const sign=(secret,timestamp,body)=>`t=${timestamp},v1=${crypto.createHmac('sha256',secret).update(`${timestamp}.${body}`).digest('hex')}`;
const json=(res,status,body)=>res.status(status).json(body);
export default async function handler(req,res){
 if(req.method!=='POST')return json(res,405,{error:'method_not_allowed'});if(String(req.headers['x-internal-webhook-key']||'')!==String(process.env.MERVEIL_INTERNAL_WEBHOOK_KEY||''))return json(res,401,{error:'unauthorized'});
 const {event_id,event_type,payload}=req.body||{};if(!event_id||!event_type)return json(res,400,{error:'event_required'});
 const targetAppId=payload?.application_id||null;const {data:hooks,error}=await supabase.from('api_webhooks').select('id,application_id,url,status,failure_count,secret_ciphertext').eq('status','active').contains('events',[event_type]);if(error)return json(res,500,{error:'database_error'});
 const results=[];for(const hook of (hooks||[]).filter(h=>!targetAppId||String(h.application_id)===String(targetAppId))){try{const secret=decryptWebhookSecret(hook.secret_ciphertext),body=JSON.stringify({id:event_id,type:event_type,data:payload||{},created_at:new Date().toISOString()}),timestamp=Math.floor(Date.now()/1000),signature=sign(secret,timestamp,body),now=new Date().toISOString();const {data:delivery,error:insertError}=await supabase.from('api_webhook_deliveries').insert({webhook_id:hook.id,event_id,event_type,payload:payload||{},attempt:1,status:'pending',signature}).select('id').single();if(insertError&&insertError.code==='23505'){results.push({webhook_id:hook.id,duplicate:true});continue;}if(insertError)throw insertError;try{const r=await fetch(hook.url,{method:'POST',headers:{'content-type':'application/json','user-agent':'Merveil-Webhooks/1.0','Merveil-Event-Id':event_id,'Merveil-Signature':signature,'Merveil-Timestamp':String(timestamp)},body,signal:AbortSignal.timeout(10000)}),text=(await r.text()).slice(0,4000),ok=r.status>=200&&r.status<300;await supabase.from('api_webhook_deliveries').update({status:ok?'delivered':'retrying',response_status:r.status,response_body:text,delivered_at:ok?now:null,finished_at:now,error_message:ok?null:`HTTP ${r.status}`,next_attempt_at:ok?null:new Date(Date.now()+60000).toISOString()}).eq('id',delivery.id);await supabase.from('api_webhooks').update({last_delivery_at:now,...(ok?{failure_count:0,last_success_at:now}:{failure_count:(hook.failure_count||0)+1,last_failure_at:now})}).eq('id',hook.id);results.push({webhook_id:hook.id,delivered:ok,status:r.status});}catch(e){await supabase.from('api_webhook_deliveries').update({status:'retrying',error_message:String(e.message||e).slice(0,1000),finished_at:now,next_attempt_at:new Date(Date.now()+60000).toISOString()}).eq('id',delivery.id);results.push({webhook_id:hook.id,delivered:false,error:'delivery_failed'});}}catch(e){results.push({webhook_id:hook.id,delivered:false,error:String(e.message||e).slice(0,200)});}}
 return json(res,202,{accepted:true,event_id,deliveries:results});
}
