import { json, requireUser, newApiKey, SCOPES, supabaseAdmin } from './_lib.js';
function body(req){return typeof req.body==='string'?JSON.parse(req.body||'{}'):(req.body||{});}
async function ensureOrg(userId){const {data,error}=await supabaseAdmin.rpc('api_ensure_personal_organization',{p_user_id:userId});if(error)throw error;return data;}
async function member(userId,organizationId){const {data,error}=await supabaseAdmin.from('api_organization_members').select('organization_id,role').eq('organization_id',organizationId).eq('user_id',userId).maybeSingle();if(error)throw error;return data;}
async function productionEntitled(organizationId){
  const {data,error}=await supabaseAdmin.from('api_subscriptions').select('status,environment,plan:api_plans(code)').eq('organization_id',organizationId).in('status',['active','trialing']).order('created_at',{ascending:false}).limit(1).maybeSingle();
  if(error)throw error;
  const code=String(data?.plan?.code||'').toLowerCase();
  return Boolean(data && data.environment==='production' && code && code!=='sandbox');
}
function ownerQuery(organizationId){return supabaseAdmin.from('api_applications').select('id,name,description,environment,key_prefix,scopes,status,redirect_uris,webhook_url,created_at,updated_at,last_used_at,organization_id').eq('organization_id',organizationId);}
export default async function handler(req,res){
  if(req.method==='OPTIONS')return json(res,204,null);const auth=await requireUser(req);if(auth.error)return json(res,401,{error:'unauthorized',message:auth.error});
  try{
    const organizationId=String(req.query?.organization_id||'').trim()||await ensureOrg(auth.user.id);const membership=await member(auth.user.id,organizationId);if(!membership)return json(res,403,{error:'organization_access_denied'});
    if(req.method==='GET'){const {data,error}=await ownerQuery(organizationId).order('created_at',{ascending:false});if(error)return json(res,500,{error:'database_error'});return json(res,200,{data,organization_id:organizationId,role:membership.role});}
    if(!['owner','admin'].includes(membership.role))return json(res,403,{error:'organization_admin_required'});
    if(req.method==='POST'){
      const b=body(req);const name=String(b.name||'').trim();const environment=b.environment==='production'?'production':'sandbox';const scopes=Array.isArray(b.scopes)?[...new Set(b.scopes.filter(s=>SCOPES.includes(s)))]:['profile:read'];const redirectUris=Array.isArray(b.redirect_uris)?b.redirect_uris.filter(u=>typeof u==='string'&&/^https:\/\//i.test(u)).slice(0,20):[];if(!name||name.length>80)return json(res,400,{error:'invalid_name'});
      if(environment==='production' && !(await productionEntitled(organizationId)))return json(res,402,{error:'production_plan_required',message:'Production credentials require an active paid Merveil API subscription. Start in sandbox, then upgrade your organization to activate production.',next:'/api/v1/organization?action=upgrade'});
      const generated=newApiKey(environment);const {data,error}=await supabaseAdmin.from('api_applications').insert({user_id:auth.user.id,organization_id:organizationId,name,description:String(b.description||'').slice(0,500)||null,environment,key_prefix:generated.prefix,key_hash:generated.hash,scopes,redirect_uris:redirectUris}).select('id,name,description,environment,key_prefix,scopes,status,redirect_uris,organization_id,created_at').single();if(error)return json(res,500,{error:'database_error'});return json(res,201,{data,api_key:generated.key,warning:'Store this API key securely. It will not be shown again.'});
    }
    const id=String(req.query?.id||'').trim();if(!id)return json(res,400,{error:'application_id_required'});const {data:app,error:lookupError}=await supabaseAdmin.from('api_applications').select('id,user_id,environment,organization_id').eq('id',id).eq('organization_id',organizationId).maybeSingle();if(lookupError||!app)return json(res,404,{error:'application_not_found'});
    if(req.method==='PATCH'){const b=body(req);if(b.environment==='production' && app.environment!=='production' && !(await productionEntitled(organizationId)))return json(res,402,{error:'production_plan_required',message:'Production credentials require an active paid Merveil API subscription.'});if(b.rotate_key===true){const generated=newApiKey(app.environment);const {error}=await supabaseAdmin.from('api_applications').update({key_prefix:generated.prefix,key_hash:generated.hash,updated_at:new Date().toISOString()}).eq('id',id).eq('organization_id',organizationId);if(error)return json(res,500,{error:'database_error'});return json(res,200,{data:{id,key_prefix:generated.prefix,organization_id:organizationId},api_key:generated.key,warning:'The previous key is now invalid. Store this new key securely; it will not be shown again.'});}const patch={};if(b.name!==undefined){const n=String(b.name).trim();if(!n||n.length>80)return json(res,400,{error:'invalid_name'});patch.name=n;}if(b.description!==undefined)patch.description=String(b.description).slice(0,500);if(Array.isArray(b.scopes))patch.scopes=[...new Set(b.scopes.filter(s=>SCOPES.includes(s)))];if(Array.isArray(b.redirect_uris))patch.redirect_uris=b.redirect_uris.filter(u=>typeof u==='string'&&/^https:\/\//i.test(u)).slice(0,20);if(b.status==='active'||b.status==='revoked')patch.status=b.status;patch.updated_at=new Date().toISOString();const {data,error}=await supabaseAdmin.from('api_applications').update(patch).eq('id',id).eq('organization_id',organizationId).select('id,name,description,environment,key_prefix,scopes,status,redirect_uris,organization_id,created_at,updated_at,last_used_at').single();if(error)return json(res,500,{error:'database_error'});return json(res,200,{data});}
    if(req.method==='DELETE'){const {error}=await supabaseAdmin.from('api_applications').update({status:'revoked',updated_at:new Date().toISOString()}).eq('id',id).eq('organization_id',organizationId);if(error)return json(res,500,{error:'database_error'});return json(res,200,{data:{id,status:'revoked',organization_id:organizationId}});}return json(res,405,{error:'method_not_allowed'});
  }catch(error){console.error('[merveil-apps]',error);return json(res,500,{error:'database_error'});}
}