import React, { useEffect, useMemo, useState } from "react";
import { createClient } from "@supabase/supabase-js";
import { Activity, Bot, Box, Braces, Check, Cloud, Code2, Database, FileCode2, GitBranch, KeyRound, LayoutDashboard, Link2, Logs, Package, Plus, Rocket, Search, Settings, ShieldCheck, Sparkles, Terminal, TestTube2, UserRound, Wrench } from "lucide-react";

const url = import.meta.env.VITE_SUPABASE_URL || "";
const key = import.meta.env.VITE_SUPABASE_ANON_KEY || import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || "";
const supabase = url && key ? createClient(url, key) : null;

const NAV = [
  ["HOME", LayoutDashboard, "blue"], ["PROJECTS", Box, "violet"], ["WORKSPACE", Code2, "cyan"],
  ["AGENTS", Bot, "purple"], ["AI MODELS", Sparkles, "pink"], ["TEMPLATES", Package, "amber"],
  ["CODE", FileCode2, "blue"], ["DATABASE", Database, "teal"], ["API", Braces, "orange"],
  ["INTEGRATIONS", Link2, "green"], ["BUILDS", Wrench, "violet"], ["TESTS", TestTube2, "pink"],
  ["DEPLOYMENTS", Rocket, "green"], ["RUNTIME", Activity, "cyan"], ["LOGS", Logs, "slate"],
  ["MONITORING", Activity, "blue"], ["API KEYS", KeyRound, "amber"],
];
const TOOLS = [["New project", Plus, "violet"], ["Create agent", Bot, "purple"], ["Database", Database, "teal"], ["GitHub", GitBranch, "blue"], ["Vercel", Cloud, "green"], ["Build", Wrench, "violet"], ["Tests", TestTube2, "pink"], ["Deploy", Rocket, "green"], ["Terminal", Terminal, "slate"]];
function Icon({ C, c="blue", s=16 }) { return <span className={`dp-icon ${c}`}><C size={s}/></span>; }

export default function DeveloperPlatformFixed() {
  const [section,setSection]=useState("HOME"), [profile,setProfile]=useState(null), [draft,setDraft]=useState(null);
  const [projects,setProjects]=useState([]), [user,setUser]=useState(null), [loading,setLoading]=useState(true), [error,setError]=useState("");
  const [connections,setConnections]=useState({supabase:Boolean(supabase),github:false,vercel:false}), [search,setSearch]=useState(false), [query,setQuery]=useState("");

  useEffect(()=>{ let live=true; (async()=>{
    if(!supabase){ setLoading(false); setError("Supabase environment is not configured."); return; }
    const {data:{user:u},error:e}=await supabase.auth.getUser();
    if(!live)return; if(e){setError(e.message);setLoading(false);return;} setUser(u);
    if(!u){setLoading(false);return;}
    const [p,pr,c]=await Promise.all([
      supabase.from("developer_profiles").select("*").eq("user_id",u.id).maybeSingle(),
      supabase.from("developer_projects").select("*").eq("owner_user_id",u.id).order("updated_at",{ascending:false}).limit(20),
      supabase.from("developer_provider_connections").select("provider,status").eq("owner_user_id",u.id)
    ]);
    if(!live)return;
    if(p.error) setError(p.error.message); else if(p.data){setProfile(p.data);setDraft(p.data);}
    if(pr.error) setError(x=>x||pr.error.message); else setProjects(pr.data||[]);
    if(!c.error) setConnections(x=>({...x,...Object.fromEntries((c.data||[]).map(v=>[String(v.provider).toLowerCase(),v.status==="connected"]))}));
    setLoading(false);
  })(); return()=>{live=false}; },[]);

  const saveProfile=async()=>{ if(!user||!supabase||!draft)return; setError(""); const payload={...draft,user_id:user.id,updated_at:new Date().toISOString()}; delete payload.id; const {data,error:e}=await supabase.from("developer_profiles").upsert(payload,{onConflict:"user_id"}).select().single(); if(e){setError(e.message);return;} setProfile(data||draft);setSection("PROFILE"); };
  const title=section.replace(/_/g," ").replace(/\b\w/g,m=>m.toUpperCase());
  if(loading) return <div className="dp-shell dp-loading"><Sparkles size={20}/> Loading Merveil Developer…</div>;
  if(!user) return <div className="dp-shell dp-auth"><ShieldCheck size={30}/><h1>Merveil Developer</h1><p>Sign in to access your developer workspace, projects and infrastructure.</p><button className="dp-btn violet" onClick={()=>window.location.assign("/")}>Return to Merveil</button></div>;
  return <div className="dp-shell">
    <header className="dp-topbar"><div className="dp-brand"><div className="dp-mark">M</div><div><strong>MERVEIL AI</strong><span>DEVELOPER</span></div></div><button className="dp-search" onClick={()=>setSearch(true)}><Search size={16}/>Search or jump to…<kbd>⌘ K</kbd></button><button className="dp-user" onClick={()=>setSection("PROFILE")}><span className="dp-avatar">{(profile?.display_name||user.email||"D")[0].toUpperCase()}</span>{profile?.display_name||user.email||"Developer"}</button></header>
    <div className="dp-body"><aside className="dp-sidebar"><div className="dp-verified"><ShieldCheck size={15}/><span>Merveil Passport</span><Check size={13}/></div><nav>{NAV.map(([n,C,c])=><button key={n} className={section===n?"active":""} onClick={()=>setSection(n)}><Icon C={C} c={c}/>{n}</button>)}</nav><div className="dp-sidebar-bottom"><button onClick={()=>setSection("PROFILE")}><Icon C={UserRound} c="cyan"/>Developer Profile</button><button onClick={()=>setSection("SETTINGS")}><Icon C={Settings} c="slate"/>Settings</button></div></aside>
    <main className="dp-main">{error&&<div className="dp-error">{error}</div>}{section==="PROFILE"?<Profile profile={profile||{}} draft={draft||profile||{}} setDraft={setDraft} save={saveProfile}/>:section==="HOME"?<Home profile={profile} projects={projects} connections={connections} go={setSection}/>:<Work title={title} section={section} projects={projects} connections={connections} query={query} setQuery={setQuery}/>}</main></div>
    {search&&<div className="dp-overlay" onClick={()=>setSearch(false)}><div className="dp-command-palette" onClick={e=>e.stopPropagation()}><div className="palette-search"><Search size={18}/><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search developer tools…"/></div>{NAV.filter(x=>x[0].includes(query.toUpperCase())||!query).slice(0,12).map(([n,C,c])=><button key={n} onClick={()=>{setSection(n);setSearch(false)}}><Icon C={C} c={c}/>{n}<kbd>↵</kbd></button>)}</div></div>}
  </div>;
}
function Home({profile,projects,connections,go}){return <><div className="dp-page-head"><div><div className="dp-eyebrow">DEVELOPER WORKSPACE · PRODUCTION</div><h1>Good evening, {profile?.display_name||"Developer"}.</h1><p>Build, test, connect and ship from one real engineering workspace.</p></div><div className="dp-head-buttons"><button className="dp-btn violet" onClick={()=>go("PROJECTS")}><Plus size={16}/>New project</button><button className="dp-btn" onClick={()=>go("WORKSPACE")}><Code2 size={16}/>Open workspace</button></div></div><section className="dp-hero-grid"><div className="dp-card dp-command-card"><div className="dp-card-title"><Sparkles size={17}/>Merveil Intelligence <b className="live-dot">LIVE</b></div><h2>What are you building?</h2><div className="dp-ai-input"><Sparkles size={17}/><input placeholder="Describe an idea, fix, build or deployment…"/><button onClick={()=>go("WORKSPACE")}><Rocket size={15}/></button></div></div><div className="dp-card dp-health"><div className="dp-card-title"><Activity size={17}/>Platform health</div>{[["Workspace",true],["Supabase",connections.supabase],["GitHub",connections.github],["Vercel",connections.vercel]].map(([n,on])=><div className="health-row" key={n}><span>{n}</span><b className={on?"":"off"}>{on?"Connected":"Not connected"}</b></div>)}</div></section><div className="dp-section-title"><h2>Projects</h2><button onClick={()=>go("PROJECTS")}>View all →</button></div>{projects.length?<section className="dp-project-grid">{projects.slice(0,8).map(p=><button className="dp-project" key={p.id} onClick={()=>go("WORKSPACE")}><div className="project-top"><Icon C={Box} c="violet"/><span>{p.stage||p.status||"Active"}</span></div><h3>{p.name}</h3><p>{p.tagline||"Merveil project"}</p></button>)}</section>:<div className="dp-empty dp-card"><Box size={24}/><h3>No projects yet</h3><p>Create your first project to populate the workspace.</p><button className="dp-btn violet" onClick={()=>go("PROJECTS")}><Plus size={15}/>Create project</button></div>}<div className="dp-section-title"><h2>Engineering tools</h2></div><section className="dp-tools">{TOOLS.map(([n,C,c])=><button className="dp-tool" key={n} onClick={()=>go(n.toUpperCase())}><Icon C={C} c={c}/><span>{n}</span><span>→</span></button>)}</section></>}
function Profile({profile,draft,setDraft,save}){return <div className="profile-page"><div className="profile-cover"/><div className="profile-identity"><span className="profile-avatar">{(profile.display_name||"D")[0].toUpperCase()}</span><div><h1>{profile.display_name||"Developer"}</h1><p>{profile.bio||"Developer on Merveil"}</p><span className="verified"><ShieldCheck size={14}/>Developer profile</span></div></div><div className="edit-panel"><label>Display name<input value={draft.display_name||""} onChange={e=>setDraft({...draft,display_name:e.target.value})}/></label><label>Bio<textarea value={draft.bio||""} onChange={e=>setDraft({...draft,bio:e.target.value})}/></label><label>Primary language<input value={draft.primary_language||""} onChange={e=>setDraft({...draft,primary_language:e.target.value})}/></label><label>Experience<select value={draft.experience_level||"expert"} onChange={e=>setDraft({...draft,experience_level:e.target.value})}><option value="beginner">Beginner</option><option value="intermediate">Intermediate</option><option value="expert">Expert</option></select></label><button className="dp-btn violet" onClick={save}>Save profile</button></div></div>}
function Work({title,section,projects,connections}){return <div className="workspace"><div className="workspace-head"><div><div className="dp-eyebrow">MERVEIL DEVELOPER</div><h1>{title}</h1><p>Real connected engineering surface. No demo project data is injected.</p></div><div className="workspace-actions"><button className="dp-btn"><Search size={15}/>Filter</button><button className="dp-btn violet"><Plus size={15}/>Create</button></div></div><div className="workspace-grid"><div className="file-tree dp-card"><b>PROJECTS</b>{projects.map(p=><div className="tree-row" key={p.id}><Box size={14}/>{p.name}</div>)}{!projects.length&&<small>No projects</small>}<hr/><b>INFRASTRUCTURE</b>{["Code","Database","API","Integrations","Builds","Tests","Deployments","Logs"].map(x=><div className="tree-row" key={x}><FileCode2 size={14}/>{x}</div>)}</div><div className="editor dp-card"><div className="editor-bar"><span>{section.toLowerCase()}</span><span>workspace</span><span className="green-text">● Connected</span></div><pre>{`MERVEIL DEVELOPER\n\nSection: ${title}\nProjects: ${projects.length}\nSupabase: ${connections.supabase?"connected":"not configured"}\nGitHub: ${connections.github?"connected":"not connected"}\nVercel: ${connections.vercel?"connected":"not connected"}\n\nSelect a project to begin engineering.`}</pre><div className="terminal"><div><Terminal size={14}/>Terminal <span>Build</span><span>Tests</span><span>Logs</span></div><code>$ merveil workspace status\n✓ application loaded\n✓ data source connected\n$ _</code></div></div><div className="ai-panel dp-card"><div className="dp-card-title"><Sparkles size={17}/>Merveil Intelligence</div><p>Project-aware actions appear here once a project is selected.</p><button className="ai-action"><Wrench size={15}/>Diagnose</button><button className="ai-action"><TestTube2 size={15}/>Generate tests</button><button className="ai-action"><Rocket size={15}/>Prepare deployment</button></div></div></div>}
